# Generated by Django 5.1.7 on 2025-06-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_brand_country_alter_product_composition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvar',
            name='volume_unit',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Единица измерения'),
        ),
    ]
