# Generated by Django 5.1.7 on 2025-06-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_productvar_volume_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvar',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Цвет'),
        ),
    ]
