# Generated by Django 5.1.7 on 2025-11-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_productvar_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card_online', 'Банковской картой онлайн'), ('cash_on_delivery', 'Наличными при получении'), ('online_payment', 'Онлайн-оплата через систему электронных платежей')], default='card_online', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(default='Адрес не указан', verbose_name='Адрес доставки'),
            preserve_default=False,
        ),
    ]
