# Generated by Django 5.1.7 on 2025-11-04 13:00

from django.db import migrations


def forwards_func(apps, schema_editor):
    Order = apps.get_model('main', 'Order')
    Profile = apps.get_model('main', 'Profile')

    for order in Order.objects.all():
        # Обновляем адрес доставки из профиля
        if order.profile.address:
            order.shipping_address = order.profile.address
        # Если адрес не указан в профиле, оставляем "Адрес не указан" (уже установлено по умолчанию)

        # Способ оплаты уже должен быть установлен по умолчанию
        order.save()

    print(f"Updated {Order.objects.count()} orders")


def reverse_func(apps, schema_editor):
    # Обратная миграция не требуется
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_add_shipping_address_payment_method'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
